{
  "abstract" : [
    {
      "text" : "A previous future failed with an error, which we don’t desire.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit",
        "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit\/EventLoopFutureQueue",
        "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError\/previousError(_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:8AsyncKit20EventLoopFutureQueueC13ContinueErrorO08previousH0yAEs0H0_pcAEmF",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "case"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "previousError"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s5ErrorP",
        "text" : "Error"
      },
      {
        "kind" : "text",
        "text" : ")"
      }
    ],
    "modules" : [
      {
        "name" : "AsyncKit"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Case",
    "symbolKind" : "case",
    "title" : "EventLoopFutureQueue.ContinueError.previousError(_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "macOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "case"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "previousError"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s5ErrorP",
              "text" : "Error"
            },
            {
              "kind" : "text",
              "text" : ")"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/asynckit\/eventloopfuturequeue\/continueerror\/previouserror(_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://edu.uky.cs.netreconlab.ParseServerSwift/documentation/AsyncKit": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "AsyncKit",
  "type" : "topic",
  "url" : "\/documentation\/asynckit"
},
"doc://edu.uky.cs.netreconlab.ParseServerSwift/documentation/AsyncKit/EventLoopFutureQueue": {
  "abstract" : [
    {
      "text" : "Allows you to queue closures that produce an ",
      "type" : "text"
    },
    {
      "code" : "EventLoopFuture",
      "type" : "codeVoice"
    },
    {
      "text" : ", so each future only gets run if the previous ones complete, succeed, or fail.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "EventLoopFutureQueue"
    }
  ],
  "identifier" : "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit\/EventLoopFutureQueue",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventLoopFutureQueue"
    }
  ],
  "role" : "symbol",
  "title" : "EventLoopFutureQueue",
  "type" : "topic",
  "url" : "\/documentation\/asynckit\/eventloopfuturequeue"
},
"doc://edu.uky.cs.netreconlab.ParseServerSwift/documentation/AsyncKit/EventLoopFutureQueue/ContinueError": {
  "abstract" : [
    {
      "text" : "Errors that get propogated based on a future’s completion status and the next appended closure’s continuation condition.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ContinueError"
    }
  ],
  "identifier" : "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ContinueError"
    }
  ],
  "role" : "symbol",
  "title" : "EventLoopFutureQueue.ContinueError",
  "type" : "topic",
  "url" : "\/documentation\/asynckit\/eventloopfuturequeue\/continueerror"
},
"doc://edu.uky.cs.netreconlab.ParseServerSwift/documentation/AsyncKit/EventLoopFutureQueue/ContinueError/previousError(_:)": {
  "abstract" : [
    {
      "text" : "A previous future failed with an error, which we don’t desire.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "previousError"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5ErrorP",
      "text" : "Error"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/edu.uky.cs.netreconlab.ParseServerSwift\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError\/previousError(_:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "EventLoopFutureQueue.ContinueError.previousError(_:)",
  "type" : "topic",
  "url" : "\/documentation\/asynckit\/eventloopfuturequeue\/continueerror\/previouserror(_:)"
}
}
}